### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by TalhaTeeTee** [richardadonnell/Upwork-Job-Scraper#87]
Only the test webhook button works and it send the test data into my make automation but even when i manually search for jobs or It search for jobs on set intervals, the webhook is not sending new job data through.

**Comment by richardadonnell** [comment]
Thank you for providing this feedback. I'm currently away from my computer for the holidays, but I'll look at this as soon as I get back!

**Comment by richardadonnell** [comment]
@TalhaTeeTee  

I appreciate your patience while I take the time to address this issue.  

When you have a moment, please open the extension settings, scroll to the bottom of the page, and copy/paste your full Activity Log text into this thread.

The extension already includes error reporting, and I believe I’ve identified the problem, but reviewing your complete Activity Log will help me confirm.

**Comment by TalhaTeeTee** [comment]
Hi Richard,
thanks for the guidelines, the extension is now working properly.
I have connected it to make and getting all the jobs in a google sheet now

**Comment by richardadonnell** [comment]
Thank you for the feedback @TalhaTeeTee - that's great to hear it's working as intended now!

Please feel free to reach out at any time in the future if you have any other issues, questions, suggestions, etc!

Happy hunting! 🎯
